---
baseurl: "https://www.dencold.com/"
languageCode: "en-us"
title: "dencold"
paginate: 5
Copyright: "All rights reserved - 2016"
canonifyurls: true

params:
  description: "fiat lux"
  cover: "/images/site/cover.jpg"
  fullCover: false
  author: "dennis"
  logo: "/images/site/S1R3withSlant.svg"
  googleAnalyticsUserID: ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink: "http://feeds.feedburner.com/..." 
  githubName: "dencold"
  twitterName: "dencold"
  hideHUGOSupport: true
  highlightjsTheme: "tomorrow-night-eighties"
  sharing:
    twitter: true
    facebook: true
    google-plus: false

author:
  dennis:
    id: "dennis"
    firstName: "Dennis"
    lastName: "Coldwell"
    location: "Berkeley, CA"
    bio: "trying to leave things better than I found them"
    thumbnail: "/images/site/avatar.jpg"

menu:
  main:
    - name: "Blog"
      weight: -120
      identifier: "blog"
      url: "/"
    - name: "About"
      weight: -110
      identifier: "about"
      url: "/about"
  
