baseurl = "http://dencold.com/"
languageCode = "en-us"
title = "dencold"
paginate = 5
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  description = "fiat lux"
  cover = "images/site/cover.jpg"
  author = "Dennis Coldwell"
  authorlocation = "Berkeley, CA"
  authorwebsite = "http://dencold.com"
  authoravatar = "images/site/avatar.jpg"
  bio= "my bio"
  logo = "images/site/logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..." 
  githubName = "dencold"
  twitterName = "dencold"
  hideHUGOSupport = true

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About"
  weight = -110
  identifier = "about"
  url = "/about"
  
