---
baseurl: "https://www.dencold.com/"
languageCode: "en-us"
title: "dencold"
theme: "hasper"
paginate: 5
Copyright: "All rights reserved - 2016"
canonifyurls: true
metaDataFormat: "yaml"

# hugo special directories. generally do *not* need to modify these
contentdir: "content"
dataDir: "data"
defaultLayout: "post"
layoutdir: "layouts"
paginatePath: "page"
publishdir: "public"
staticdir: "static"
themesdir: "themes"

params:
  description: "fiat lux"
  cover: "/images/site/cover.jpg"
  fullCover: false
  author: "dennis"
  logo: "/images/site/S1R3withSlant.svg"
  googleAnalyticsUserID: ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink: "http://feeds.feedburner.com/..." 
  githubName: "dencold"
  twitterName: "dencold"
  hideHUGOSupport: true
  highlightjsTheme: "tomorrow-night-eighties"
  sharing:
    twitter: true
    facebook: true
    google-plus: false

author:
  dennis:
    id: "dennis"
    firstName: "Dennis"
    lastName: "Coldwell"
    location: "Berkeley, CA"
    bio: "trying to leave things better than I found them"
    thumbnail: "/images/site/avatar.jpg"

menu:
  main:
    - name: "Home"
      weight: -120
      identifier: "home"
      url: "/"
    - name: "About"
      weight: -110
      identifier: "about"
      url: "/author/dennis"
    - name: "Posts"
      weight: -100
      identifier: "posts"
      url: "/post"
  
